version: "3.7"

services:
  app:
    build:
      context: .
      target: production
    container_name: lanco-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
