version: "3.7"

services:
  app:
    build:
      context: .
    container_name: lanco-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.env:/app/.env:ro
      - ./app:/app/app
      - ./data:/app/data
      - ./logs:/app/logs
