[tool.poetry]
name = "lanco-bot"
version = "0.1.0"
description = ""
authors = ["Nate Shoffner <nate.shoffner@gmail.com>"]
readme = "README.md"
packages = [{include = "app"}]

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.3.2"
lcwc = "^0.12.2"
pydantic = "^2.4.2"
peewee = "^3.17.0"
python-dotenv = "^1.0.0"
aiofiles = "^23.2.1"
pytz = "^2023.3.post1"
toml = "^0.10.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
